### ISSUE TITLE
multiple ignoreSources dont work

### ISSUE THREAD

**Issue by Laubeee** [chbrandt/dachs-doc#10]
multiple `ignoreSources` elements as in [this example](http://svn.ari.uni-heidelberg.de/svn/gavo/hdinputs/bgds/q.rd) don't seem to work (anymore?) only the last element is "used"

Tested on debian, reproducible with docker dachs:buster.
Is there an alternative way to achieve the same result..?

**Comment by msdemlei** [comment]
On Tue, Sep 22, 2020 at 06:11:07AM -0700, Silvan Laube wrote:
> multiple `ignoreSources` elements as in [this
> example](http://svn.ari.uni-heidelberg.de/svn/gavo/hdinputs/bgds/q.rd)
> don't seem to work (anymore?) only the last element is "used"

It has never worked -- you can tell because in the reference it says
"contains Element ignoreSources" in
https://docs.g-vo.org/DaCHS/ref.html#element-sources; for list-valued
children it would say "and may be repeated zero or more times".

That this doesn't give an error is that DaCHS uses child overwriting
as a feature in some places (in particular when you override
streams).  It's really tricky to tell apart intended and non-indended
overwrites (see also the box on "Attributes and Elements in DaCHS" in
the tutorial).

So, the bdgs RD is erroneous; fortunately, the master* files were
gone, so it didn't bite me (but then I haven't noticed the trouble
either).

> Tested on debian, reproducible with docker dachs:buster.
> Is there an alternative way to achieve the same result..

Depends.  If you look at
https://docs.g-vo.org/DaCHS/ref.html#element-ignoresources you will
see that you can repeat patterns in a single ignoreSources element.

You cannot repeat fromdb and fromfile.

You can mix the different attributes.  So, if bgds still needed to
exclude master frames, it would use:

```
<ignoreSources 
  pattern="master*"
  fromdb="select accref from \schema.data"/>
```

Does any of that cover your use case?

**Comment by Laubeee** [comment]
hmm in this case I need multiple patterns (to exclude erroneous files) and one fromdb to prevent re-importing..

**Comment by Laubeee** [comment]
Is something like this possible (I think I haven't tried THAT yet):
```xml
<ignoreSources fromdb="...">
  <pattern>...</pattern>
  <pattern>...</pattern>
  <pattern>...</pattern>
</ignoreSources>
```

**Comment by msdemlei** [comment]
On Tue, Sep 22, 2020 at 07:54:21AM -0700, Silvan Laube wrote:
> Is something like this possible (I think I haven't tried THAT yet):
> ```xml
> <ignoreSources fromdb="...">
>   <pattern>...</pattern>
>   <pattern>...</pattern>
>   <pattern>...</pattern>
> </ignoreSources>
> ```

Yes, that is the idea.

**Comment by Laubeee** [comment]
k thx!👍
hope its okay I keep raising issues, even if they're not actual issues sometimes.. this can be closed

**Comment by msdemlei** [comment]
On Tue, Sep 22, 2020 at 08:18:01AM -0700, Silvan Laube wrote:
> hope its okay I keep raising issues, even if they're not actual
> issues sometimes.. this can be closed 

Now that you mention it, I think I'd rather have these issues on
dachs-users, because I think more people see it there (and we're
stripping off a bit of github's behavioural surplus).

But then, whatever works for you.
