### ISSUE TITLE
Clarification of pattern usage

### ISSUE THREAD

**Issue by Laubeee** [chbrandt/dachs-doc#11]
The [doc](https://dachs-doc.readthedocs.io/ref.html#element-sources) states that `pattern` can contain shell patterns. However it is unclear how the whole thing is handeled also in combination with `recurse`. 

Given I have a folder structure `/data/yyyy/mm/dd/filename`, and the pattern `/data/1990/*.fits` with `recurse=True` gives all `.fits` for the subfolder 1990, my intuition for a pattern for all 19* folders would be to use something like `/data/19*.fits` or `/data/19*/*.fits`, or even `/data/19??/*.fits` but none of these work. What does work is the full pattern, like so: `/data/19??/??/??/*.fits` or `/data/19*/*/*/*.fits`, which makes the `recurse` option obsolete.

It seems to me `recurse` only works for that part of the pattern-path that doesn't contain any matching-characters... is that so? I think this should be clarified in the docs as well..

**Comment by msdemlei** [comment]
On Tue, Oct 20, 2020 at 03:13:01AM -0700, Silvan Laube wrote:
> The
> [doc](https://dachs-doc.readthedocs.io/ref.html#element-sources)
> states that `pattern` can contain shell patterns. However it is
> unclear how the whole thing is handeled also in combination with
> `recurse`. 
> 
> Given I have a folder structure `/data/yyyy/mm/dd/filename`, and
> the pattern `/data/1990/*.fits` with `recurse=True` gives all
> `.fits` for the subfolder 1990, my intuition for a pattern for all
> 19* folders would be to use something like `/data/19*.fits` or
> `/data/19*/*.fits`, or even `/data/19??/*.fits` but none of these
> work. What does work is the full pattern, like so:
> `/data/19??/??/??/*.fits` or `/data/19*/*/*/*.fits`, which makes
> the `recurse` option obsolete.

The way recurse works is that it splits off the directory parts and
then expands each head into all directories below it.

Hence, as with shell patterns, the wildcards can never be slashes.
Thus, `data/19*fits` is out for what you're trying to do (and of
course all this will end up all wrong if you have a leading slash;
but I think that's just typos here).

Right now, during this expansion wildcards are not expanded.
That's why the expectation fails that `data/19*/*.fits` would include
`data/1991/04/*.fits`.  Which I think is a reasonable expectation.
I'm also not terribly worried about changing the behaviour here --
this is, really, only seen offline, and constructing cases in which
that rains on someone's parade seems hard.

I think it's also not hard to implement; actually, I'd be grateful if
you could try it and see if the following leads to the behaviour you
expect.  You'd have to patch dddef.py, which you'll probably find in
/usr/lib/python3/dist-packages/gavo/rscdef/dddef.py

The patch would be:

```
Index: gavo/rscdef/dddef.py
===================================================================
--- gavo/rscdef/dddef.py	(revision 7721)
+++ gavo/rscdef/dddef.py	(working copy)
@@ -16,6 +16,7 @@
 import datetime
 import fnmatch
 import glob
+import itertools
 import os
 
 from gavo import base
@@ -211,7 +212,8 @@
 		things will happen if the directory graph contains cycles.
 		"""
 		res = []
-		for root in dirParts:
+		for root in itertools.chain.from_iterable(
+				glob.glob(d) for d in dirParts):
 			for root, dirs, files in os.walk(root):
 				if ignoreDotDirs:
 					if os.path.basename(root).startswith("."):
```

**Comment by Laubeee** [comment]
I tried the patch and it works fine :)

**Comment by Laubeee** [comment]
ah yes and also: the leading `/` is not a typo... why would that fail? works perfectly.. I mounted a NAS on `/data`. The "real" path to the data of one specific instrument is longer though.

**Comment by msdemlei** [comment]
On Tue, Oct 20, 2020 at 04:57:58AM -0700, Silvan Laube wrote:
> ah yes and also: the leading `/` is not a typo... why would that
> fail? works perfectly.. I mounted a NAS on `/data`. The "real" path
> to the data of one specific instrument is longer though.

Ah, ok.  Yes, if the data actually *is* outside of the resdir, then
that's of course the right way to do it.

In general, though, I'm advising against pulling data from somewhere
else than inputsDir; it makes DaCHS' accref calculation haphazard, to
start with, and of course it spoils the IMHO highly desirable
property that if you look at a resdir, you're seeing all there is to
a service.

What I recommend instead if you have large, quasi-external data
collections: symlinks to mount points, or having the mount points in
the resdir in the first place (but then only with a solid notice to
that effect in the README...).

**Comment by msdemlei** [comment]
I think this issue is reasonably well addressed, right?  To keep things tidy, I'm closing, but feel free to re-open if there's more we should be doing.
